package com.macdougallg.cozmoplay.protocol.messages

import com.macdougallg.cozmoplay.types.CubeLightConfig
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Builds raw payload bytes for each outbound Cozmo command message.
 *
 * Cozmo uses a CLAD (C-Like Autogenerated Data) binary format, not standard protobuf,
 * for most messages. Fields are packed little-endian in a defined order matching the
 * PyCozmo clad/ message definitions.
 *
 * Each function returns a ByteArray suitable for passing to [com.macdougallg.cozmoplay.protocol.framing.FrameCodec.encode].
 *
 * Reference: PyCozmo clad/robot/messaging.py
 */
object MessageBuilder {

    // ── Connection ────────────────────────────────────────────────────────────

    /** CONNECT — initiates handshake. Version field matches PyCozmo client version. */
    fun connect(): ByteArray {
        val buf = ByteBuffer.allocate(2).order(ByteOrder.LITTLE_ENDIAN)
        buf.putShort(2) // client protocol version
        return buf.array()
    }

    /** DISCONNECT — clean shutdown notification. No payload. */
    fun disconnect(): ByteArray = ByteArray(0)

    /**
     * PING — keepalive. Sent every 500ms while connected.
     * @param counter Monotonically increasing ping sequence number.
     * @param timestamp System.currentTimeMillis() at send time.
     */
    fun ping(counter: UInt, timestamp: Long): ByteArray {
        val buf = ByteBuffer.allocate(12).order(ByteOrder.LITTLE_ENDIAN)
        buf.putInt(counter.toInt())
        buf.putLong(timestamp)
        return buf.array()
    }

    // ── Drive ─────────────────────────────────────────────────────────────────

    /**
     * DRIVE_WHEELS — direct wheel speed control.
     * @param leftMmps Left wheel speed mm/s (-220 to 220).
     * @param rightMmps Right wheel speed mm/s (-220 to 220).
     */
    fun driveWheels(leftMmps: Float, rightMmps: Float): ByteArray {
        val buf = ByteBuffer.allocate(16).order(ByteOrder.LITTLE_ENDIAN)
        buf.putFloat(leftMmps.coerceIn(-220f, 220f))
        buf.putFloat(rightMmps.coerceIn(-220f, 220f))
        buf.putFloat(0f) // lwheel_accel — 0 for immediate
        buf.putFloat(0f) // rwheel_accel — 0 for immediate
        return buf.array()
    }

    /** STOP_ALL_MOTORS — immediate halt. No payload. */
    fun stopAllMotors(): ByteArray = ByteArray(0)

    // ── Head ──────────────────────────────────────────────────────────────────

    /**
     * SET_HEAD_ANGLE — absolute head position.
     * @param angleRad Target angle in radians (-0.44 to 0.78).
     */
    fun setHeadAngle(angleRad: Float): ByteArray {
        val buf = ByteBuffer.allocate(16).order(ByteOrder.LITTLE_ENDIAN)
        buf.putFloat(angleRad.coerceIn(-0.44f, 0.78f))
        buf.putFloat(10f)  // max_speed rad/s
        buf.putFloat(10f)  // accel rad/s²
        buf.putFloat(0f)   // duration (0 = use speed/accel)
        return buf.array()
    }

    /**
     * MOVE_HEAD — continuous movement at given speed.
     * @param speedRadPerSec Speed in rad/s. Pass 0f to stop.
     */
    fun moveHead(speedRadPerSec: Float): ByteArray {
        val buf = ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN)
        buf.putFloat(speedRadPerSec)
        return buf.array()
    }

    // ── Lift ──────────────────────────────────────────────────────────────────

    /**
     * SET_LIFT_HEIGHT — absolute lift position.
     * @param heightMm Target height in mm (32 to 92).
     */
    fun setLiftHeight(heightMm: Float): ByteArray {
        val buf = ByteBuffer.allocate(16).order(ByteOrder.LITTLE_ENDIAN)
        buf.putFloat(heightMm.coerceIn(32f, 92f))
        buf.putFloat(10f)  // max_speed
        buf.putFloat(10f)  // accel
        buf.putFloat(0f)   // duration
        return buf.array()
    }

    /**
     * MOVE_LIFT — continuous lift movement.
     * @param speedRadPerSec Speed in rad/s. Pass 0f to stop.
     */
    fun moveLift(speedRadPerSec: Float): ByteArray {
        val buf = ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN)
        buf.putFloat(speedRadPerSec)
        return buf.array()
    }

    // ── Animations ────────────────────────────────────────────────────────────

    /**
     * PLAY_ANIMATION — play a named animation clip.
     * @param name Animation name string (null-terminated).
     */
    fun playAnimation(name: String): ByteArray {
        val nameBytes = name.toByteArray(Charsets.UTF_8)
        val buf = ByteBuffer.allocate(nameBytes.size + 1).order(ByteOrder.LITTLE_ENDIAN)
        buf.put(nameBytes)
        buf.put(0) // null terminator
        return buf.array()
    }

    /**
     * PLAY_ANIMATION_GROUP — play a random animation from a named group.
     * @param groupName Group name string (null-terminated).
     */
    fun playAnimationGroup(groupName: String): ByteArray = playAnimation(groupName)

    // ── Cube Lights ───────────────────────────────────────────────────────────

    /**
     * SET_CUBE_LIGHTS — set light pattern on a cube.
     * @param objectId Robot-internal object ID.
     * @param lights Up to 4 light configs (one per corner LED).
     */
    fun setCubeLights(objectId: Int, lights: List<CubeLightConfig>): ByteArray {
        // Each light: color(4) + onPeriodMs(4) + offPeriodMs(4) + transitionMs(4) = 16 bytes
        // Header: objectId(4) + count(1) = 5 bytes
        val lightCount = lights.size.coerceAtMost(4)
        val buf = ByteBuffer.allocate(5 + lightCount * 16).order(ByteOrder.LITTLE_ENDIAN)
        buf.putInt(objectId)
        buf.put(lightCount.toByte())
        lights.take(lightCount).forEach { light ->
            buf.putInt(light.color)
            buf.putInt(light.onPeriodMs)
            buf.putInt(light.offPeriodMs)
            buf.putInt(light.transitionMs)
        }
        return buf.array()
    }

    // ── Cube Actions ──────────────────────────────────────────────────────────

    /**
     * PICKUP_OBJECT — command robot to pick up a cube.
     * @param objectId Robot-internal object ID.
     */
    fun pickupObject(objectId: Int): ByteArray {
        val buf = ByteBuffer.allocate(5).order(ByteOrder.LITTLE_ENDIAN)
        buf.putInt(objectId)
        buf.put(1) // use_pre_dock_pose = true
        return buf.array()
    }

    /** PLACE_OBJECT — command robot to place held object. No object ID needed. */
    fun placeObject(): ByteArray {
        val buf = ByteBuffer.allocate(1).order(ByteOrder.LITTLE_ENDIAN)
        buf.put(1) // use_pre_dock_pose = true
        return buf.array()
    }

    /**
     * ROLL_OBJECT — command robot to roll a cube.
     * @param objectId Robot-internal object ID.
     */
    fun rollObject(objectId: Int): ByteArray {
        val buf = ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN)
        buf.putInt(objectId)
        return buf.array()
    }

    // ── Camera ────────────────────────────────────────────────────────────────

    /**
     * ENABLE_CAMERA — start or stop the camera stream.
     * @param enabled True to start streaming, false to stop.
     */
    fun enableCamera(enabled: Boolean): ByteArray {
        val buf = ByteBuffer.allocate(1).order(ByteOrder.LITTLE_ENDIAN)
        buf.put(if (enabled) 1.toByte() else 0.toByte())
        return buf.array()
    }

    // ── Freeplay ──────────────────────────────────────────────────────────────

    /**
     * ENABLE_FREEPLAY — start or stop autonomous behaviour mode.
     * @param enabled True to enable freeplay, false to disable.
     */
    fun enableFreeplay(enabled: Boolean): ByteArray {
        val buf = ByteBuffer.allocate(1).order(ByteOrder.LITTLE_ENDIAN)
        buf.put(if (enabled) 1.toByte() else 0.toByte())
        return buf.array()
    }
}
